
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svrooqcjicmkilplmtim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cm9vcWNqaWNta2lscGxtdGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTU2ODUsImV4cCI6MjA2MDI3MTY4NX0.6WlG9oStZFB7inY7VWZT_en9xh-R4cBjPWNFJKPvEjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
